# Generated by Django 2.2.7 on 2019-11-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UddinaVada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TatteIdli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RoundIdli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RiceBath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Puliyogare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Paddu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MasalaVada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Mandakki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Kharabath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Kesaribath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DosaD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Bisibelebath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Avalakki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_step', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=50)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Person')),
            ],
        ),
    ]
